Optimize product list view queries
mirumee/saleor-dashboard pull request #1016
Opened 2021-03-17 14:14 UTC by jwm0

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.
1. [ ] The changes are tested in different browsers (Chrome, Firefox, Safari).
1. [ ] The changes are tested in light and dark mode.

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-03-17 14:14 UTC, patrys commented
Task linked: [SALEOR-2676 Optimize product list queries](https://app.clickup.com/t/2549495/SALEOR-2676)

2021-04-07 10:15 UTC, dominik-zeglen commented on src/components/SingleAutocompleteSelectField/SingleAutocompleteSelectField.tsx
> +    });
Why?

2021-04-07 10:16 UTC, dominik-zeglen approved these changes

2021-04-08 09:32 UTC, mmarkusik requested changes

2021-04-08 09:32 UTC, mmarkusik commented on src/products/views/ProductList/ProductList.tsx
> +    initialFilterAttributes?.attributes?.edges?.map(edge => edge.node) || [],
Considering how many times we do this `edges?.map(edge => edge.node)` in the app, maybe we can add a util function?

2021-04-08 09:33 UTC, mmarkusik approved these changes

2021-04-08 16:14 UTC, merged