Support attributes values for dropdown & multiselect.
mirumee/saleor-dashboard pull request #1017
Opened 2021-03-19 07:51 UTC by piotrgrundas

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.
1. [ ] The changes are tested in different browsers (Chrome, Firefox, Safari).
1. [ ] The changes are tested in light and dark mode.

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-03-22 10:19 UTC, dominik-zeglen commented
Not ringing any bells what it should be doing. Can you point to clickup ticket and link affected storybook pages?

2021-03-22 10:49 UTC, piotrgrundas commented
@dominik-zeglen It's required for external integration.

2021-03-22 16:10 UTC, orzechdev reviewed
@piotrgrundas I don't understand what do you mean by "it's required for external integration". It doesn't explain to me any changes added here.

Also, name of the commit `#` doesn't explain anything.

2021-03-29 08:48 UTC, dominik-zeglen commented on src/attributes/components/AttributeValues/AttributeValues.tsx
> +                  {value?.name ?? <Skeleton />}
I thought I'd never see this operator 😮

2021-03-29 08:49 UTC, dominik-zeglen approved these changes

2021-03-29 13:49 UTC, jwm0 requested changes

2021-03-29 13:49 UTC, jwm0 commented on src/attributes/components/AttributeValueEditDialog/AttributeValueEditDialog.tsx
> +    name: maybe(() => attributeValue.name, ""),
use this opportunity to get rid off `maybe`

2021-04-16 12:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mirumee/saleor-dashboard?pullRequest=1017) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mirumee/saleor-dashboard?pullRequest=1017) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mirumee/saleor-dashboard?pullRequest=1017) it.</sub>

2021-06-07 21:23 UTC, closed without merging