Saleor 2699 tests for home page
mirumee/saleor-dashboard pull request #1019
Opened 2021-03-19 11:39 UTC by karola312

I want to merge this change because I created two more tests for home page & I change API_URI in PR comment to mach new qa environment.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.
1. [ ] The changes are tested in different browsers (Chrome, Firefox, Safari).
1. [ ] The changes are tested in light and dark mode.

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

2021-03-19 11:39 UTC, patrys commented
Task linked: [SALEOR-2699 Tests for home page](https://app.clickup.com/t/2549495/SALEOR-2699)

2021-03-19 12:09 UTC, cmiacz commented on .github/PULL_REQUEST_TEMPLATE.md
> -API_URI=https://master.staging.saleor.cloud/graphql/
Pleas update also test-env workflow:
https://github.com/mirumee/saleor-dashboard/blob/7bc4bc66962e242715605637a1ca0536d76da53e/.github/workflows/test-env-deploy.yml#L62

2021-03-22 08:51 UTC, cmiacz approved these changes

2021-03-22 09:40 UTC, mmarkusik requested changes
Maybe remove `cypress/apiRequests/Staff.js` since empty?

2021-03-23 08:45 UTC, mmarkusik approved these changes

2021-03-23 10:14 UTC, merged