Add payment events to webhooks
mirumee/saleor-dashboard pull request #1021
Opened 2021-03-22 09:17 UTC by maarcingebala

This PR adds payment webhooks. See related backend PR: https://github.com/mirumee/saleor/pull/7044

**PR intended to be tested with API branch:** `sync-webhook`

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.
1. [ ] The changes are tested in different browsers (Chrome, Firefox, Safari).
1. [ ] The changes are tested in light and dark mode.

### Test environment config

API_URI=https://sync-webhook.api.saleor.rocks/graphql/

2021-04-16 12:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mirumee/saleor-dashboard?pullRequest=1021) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mirumee/saleor-dashboard?pullRequest=1021) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mirumee/saleor-dashboard?pullRequest=1021) it.</sub>

2021-05-19 17:14 UTC, orzechdev requested changes
please run `npm run extract-messages`

2021-05-20 07:51 UTC, jwm0 requested changes
Snapshot tests are failing, run the following script in root dir:
```
npx jest src/storybook/Stories.test.ts --updateSnapshot
```

2021-05-20 09:02 UTC, orzechdev approved these changes

2021-05-21 07:37 UTC, jwm0 approved these changes

2021-06-08 10:33 UTC, merged