Update schema
mirumee/saleor-dashboard pull request #1029
Opened 2021-03-29 09:56 UTC by dominik-zeglen

I want to merge this change because it updates schema to contain changes made in mirumee/saleor/pull/6301
Note: build on top of #1028 

**PR intended to be tested with API branch:** email_interface_as_plugin

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [x] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [x] Changes are mentioned in the changelog.
1. [ ] The changes are tested in different browsers (Chrome, Firefox, Safari).
1. [ ] The changes are tested in light and dark mode.

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

2021-03-29 09:57 UTC, patrys commented
Task linked: [SALEOR-2640 Add new webhook event - Notify to dashboard section](https://app.clickup.com/t/2549495/SALEOR-2640)

2021-03-29 09:57 UTC, patrys commented
Task linked: [SALEOR-2775 Rename mutation responsible for sending an invoice](https://app.clickup.com/t/2549495/SALEOR-2775)

2021-03-29 13:46 UTC, orzechdev approved these changes

2021-03-30 08:07 UTC, jwm0 requested changes

2021-03-30 08:07 UTC, jwm0 commented on src/webhooks/components/WebhookEvents/WebhookEvents.tsx
> +    [WebhookEventTypeEnum.NOTIFY_USER]: intl.formatMessage({
Run msg extraction

2021-03-31 13:11 UTC, merged