Saleor 2551/allow assigning channels to shipping zones
mirumee/saleor-dashboard pull request #1049
Opened 2021-04-06 10:11 UTC by mmarkusik

I want to merge this change because it adds ability to assign channels to shipping zones.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [x] This code contains UI changes
2. [x] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [x] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://feature-variants-and-shipping-zones-per-channel.api.saleor.rocks/graphql/

2021-04-06 10:11 UTC, patrys commented
Task linked: [SALEOR-2551 Allow assigning channels to shipping zones](https://app.clickup.com/t/2549495/SALEOR-2551)

2021-04-06 10:11 UTC, patrys commented
Task linked: [SALEOR-2552 Allow assigning shipping zones to channels](https://app.clickup.com/t/2549495/SALEOR-2552)

2021-04-07 08:20 UTC, orzechdev approved these changes

2021-04-08 08:37 UTC, dominik-zeglen commented on src/shipping/components/ShippingZoneDetailsPage/utils.ts
> +export const getInitialFormData = (
:+1:

2021-04-08 08:40 UTC, dominik-zeglen requested changes

2021-04-08 08:40 UTC, dominik-zeglen commented on src/shipping/components/ShippingZoneSettingsCard/ShippingZoneSettingsCard.stories.tsx
> +const props = {
Can we type it instead of its fields?

2021-04-08 09:47 UTC, maarcingebala commented
@jwm0 @mmarkusik I suggest that we first merge this PR to the feature branch and then we'll do the QA, so that we have a full feature working on the feature branch.

2021-04-09 07:44 UTC, merged