Saleor 2559/add channels to plugin list view
mirumee/saleor-dashboard pull request #1083
Opened 2021-04-27 12:36 UTC by mmarkusik

I want to merge this change because it adds channels to plugin list view

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://feature-plugins-per-channel.api.saleor.rocks/graphql/

2021-04-27 12:36 UTC, patrys commented
Task linked: [SALEOR-2559 Handle channels in Plugins List View](https://app.clickup.com/t/2549495/SALEOR-2559)

2021-04-29 09:07 UTC, dominik-zeglen requested changes

2021-04-29 09:22 UTC, mmarkusik commented on src/storybook/stories/plugins/PluginDetailsPage.tsx
> +        // configuration: null
My bad, should have explained. The commented out stuff are things that overlap with [this pr](https://github.com/mirumee/saleor-dashboard/pull/1081) and will be properly removed or uncommented in feature branch.

2021-04-29 09:43 UTC, orzechdev approved these changes

2021-05-04 11:21 UTC, dominik-zeglen approved these changes

2021-05-04 12:29 UTC, merged