Reduce bundle size
mirumee/saleor-dashboard pull request #1103
Opened 2021-05-11 08:22 UTC by dominik-zeglen

I want to merge this change because it reduces bundle size and slightly optimizes build time. It also adds bundle analyzing tools which are available by passing `ANALYZE=1` as an environment variable, like this:
```
$ ANALYZE=1 npm run build
```

**PR intended to be tested with API branch:** master

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

2021-05-11 09:47 UTC, jwm0 commented on package.json
> +    "babel-plugin-lodash": "^3.3.4",
These plugins are unused

2021-05-11 11:26 UTC, dominik-zeglen commented on package.json
> +    "babel-plugin-lodash": "^3.3.4",
Right, cleanup

2021-05-11 11:31 UTC, dominik-zeglen commented on .eslintrc.json
> +        "paths": ["@material-ui/core", "lodash"]
Not really, it's optimized only for production build, but dev build has everything bundled in it, increasing build time - if ran only once it's not something developer would be concerned, but if one restarts it few times in a day (like I often do) it's a improvement. Lodash on the other hand does not support it at all.

2021-05-11 15:31 UTC, orzechdev approved these changes

2021-05-13 07:18 UTC, mmarkusik approved these changes

2021-05-13 13:11 UTC, jwm0 requested changes

2021-05-13 13:11 UTC, jwm0 commented on .eslintrc.json
> +        "paths": ["@material-ui/core", "lodash"]
As discussed internally we'll want to stick with root material-ui imports.

2021-05-13 15:36 UTC, jwm0 approved these changes

2021-05-14 08:15 UTC, merged