Fix logo appearing too high on screen when loading login
mirumee/saleor-dashboard pull request #1130
Opened 2021-05-31 10:19 UTC by mmarkusik

I want to merge this change because it fixes saleor logo appearing too high on the screen when logging in

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [x] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

2021-05-31 10:19 UTC, patrys commented
Task linked: [SALEOR-3477 Saleor logo is cut when loading state is displayed](https://app.clickup.com/t/2549495/SALEOR-3477)

2021-05-31 10:36 UTC, dominik-zeglen approved these changes

2021-05-31 11:58 UTC, orzechdev approved these changes

2021-06-01 07:07 UTC, pwgryglak requested changes
Looks ok

2021-06-01 12:17 UTC, merged