Variant attribute values pagination
mirumee/saleor-dashboard pull request #1133
Opened 2021-05-31 16:39 UTC by orzechdev

I want to merge this change because... it adds variant attribute values pagination support.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://saleor-3071-paginate-attributes.api.saleor.rocks/graphql/

2021-05-31 16:39 UTC, patrys commented
Task linked: [SALEOR-3347 Add pagination to attribute values selection card in variant details pages](https://app.clickup.com/t/2549495/SALEOR-3347)

2021-05-31 16:39 UTC, patrys commented
Task linked: [SALEOR-3109 Use pagination on attribute values](https://app.clickup.com/t/2549495/SALEOR-3109)

2021-06-03 20:07 UTC, jwm0 approved these changes

2021-06-07 07:29 UTC, dominik-zeglen requested changes

2021-06-07 07:29 UTC, dominik-zeglen commented on src/products/components/ProductVariantCreatorPage/ProductVariantCreatorPage.tsx
> +        width: `calc(100vw - ${drawerWidthExpanded + theme.spacing(6)}px)`,
```suggestion
        width: `calc(100vw - ${drawerWidthExpanded}px - ${theme.spacing(6)}px)`,
```
Makes it easier to switch spacing unit to rems in future

2021-06-07 07:29 UTC, dominik-zeglen commented on src/products/components/ProductVariantCreatorPage/ProductVariantCreatorPage.tsx
> +        maxWidth: theme.breakpoints.width("lg") - theme.spacing(6)
For the same reason as above, please use calc

2021-06-07 07:29 UTC, dominik-zeglen commented on src/products/components/ProductVariantCreatorPage/ProductVariantCreatorValues.tsx
> +                onClick={() => onAttributeSelect(attribute.id)}
I get a feeling that it should be named `onFocus`

2021-06-07 07:32 UTC, pwgryglak requested changes
Looks good, but for example in attribute 0705TestVAtt, o na product level I can't get to values from 21 to 27 via dropdown. Plus each time the values load I am transferred to top of the list. It's poor UX

2021-06-07 07:59 UTC, eCzerniak approved these changes

2021-06-07 13:42 UTC, pwgryglak approved these changes
On Safari looks good, Still experiencing on Chrome but I experience issues on Chrome that nobody else does so - Approve

2021-06-07 14:56 UTC, dominik-zeglen approved these changes

2021-06-08 06:58 UTC, merged