Saleor 3087 display attribute values in filter list
mirumee/saleor-dashboard pull request #1152
Opened 2021-06-10 09:20 UTC by orzechdev

I want to merge this change because... it adds more attribute values fetching.

**PR intended to be tested with API branch:**  master

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

2021-06-10 09:20 UTC, patrys commented
Task linked: [SALEOR-3087 Display attribute values in filter list](https://app.clickup.com/t/2549495/SALEOR-3087)

2021-06-10 12:29 UTC, eCzerniak approved these changes

2021-06-11 08:05 UTC, pwgryglak approved these changes
looks ok

2021-06-11 08:33 UTC, mmarkusik requested changes

2021-06-11 08:54 UTC, orzechdev commented on src/products/queries.ts
> +  never
Query doesn't have variables anymore.

2021-06-11 09:11 UTC, orzechdev commented on src/components/Filter/FilterContent/FilterContentBody.tsx
> -  if (!filter?.active) {
No, it's old way of opening content body of the filter.

2021-06-11 10:27 UTC, SektorDV approved these changes

2021-06-14 13:16 UTC, mmarkusik approved these changes

2021-06-14 13:31 UTC, merged