fix multiselect dropdowns in variant creator
mirumee/saleor-dashboard pull request #1188
Opened 2021-06-22 15:57 UTC by SektorDV

I want to merge this change because it fixes the issues present when there's more than one multiselect on the variant creator page.

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

2021-06-22 15:57 UTC, patrys commented
Task linked: [SALEOR-3617 Dropdowns bug](https://app.clickup.com/t/2549495/SALEOR-3617)

2021-08-05 08:32 UTC, dominik-zeglen requested changes
I don't think it's the right approach - passing attribute values if the attribute id matches the one used by query and empty array if not makes more sense (and it's easier to understand what is actually happening in there) than using memoization with deep compare + onBlur handler

2021-08-05 08:32 UTC, dominik-zeglen commented on src/products/components/ProductVariantCreatorPage/ProductVariantCreatorValues.tsx
> +import _ from "lodash";
```suggestion
import isEqual from "lodash/isEqual";
```

2021-08-05 09:53 UTC, jwm0 commented
> I don't think it's the right approach - passing attribute values if the attribute id matches the one used by query and empty array if not makes more sense (and it's easier to understand what is actually happening in there) than using memoization with deep compare + onBlur handler

In general I believe the issue is not with the component itself but rather the way we're it. Single root level state for multiple selects doesn't work. Having it as a single state is fine but it should be persisted inside some key to maintain the cache and have a clear seperation. (using the select `name` as a key should be possible)

2021-08-09 09:58 UTC, jwm0 requested changes
See my above comment

2021-08-11 09:46 UTC, closed without merging