Fix forbidden null value sending
mirumee/saleor-dashboard pull request #1201
Opened 2021-06-30 22:07 UTC by orzechdev

I want to merge this change because... it fixes forbidden null sending as an attribute value.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

2021-06-30 22:07 UTC, patrys commented
Task linked: [SALEOR-3700 Dashboard sends [null] as input where null is forbidden](https://app.clickup.com/t/2549495/SALEOR-3700)

2021-07-01 07:51 UTC, jwm0 requested changes

2021-07-01 07:51 UTC, jwm0 commented on schema.graphql
> +  channel: String
Update the schema to latest version

2021-07-01 07:51 UTC, jwm0 commented on src/attributes/utils/handlers.ts
> +      attribute.value[0] === "" || attribute.value[0] === undefined
How about a null value?

2021-07-01 09:31 UTC, orzechdev commented on src/attributes/utils/handlers.ts
> +      attribute.value[0] === "" || attribute.value[0] === undefined
Sure, also added

2021-07-01 09:40 UTC, jwm0 approved these changes

2021-07-01 10:14 UTC, eCzerniak approved these changes

2021-07-01 11:20 UTC, merged