Fix content type validation in create page view
mirumee/saleor-dashboard pull request #1205
Opened 2021-07-02 09:54 UTC by orzechdev

I want to merge this change because... it prevents page from saving if content type is not provided.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

2021-07-02 09:54 UTC, patrys commented
Task linked: [SALEOR-3590 Saving a page without providing content type crashes](https://app.clickup.com/t/2549495/SALEOR-3590)

2021-07-05 08:46 UTC, dominik-zeglen requested changes

2021-07-05 08:46 UTC, dominik-zeglen commented on src/pages/components/PageDetailsPage/form.tsx
> +    disabled,
I'm not sure about this. How about `isValid` or just `valid`?

2021-07-07 07:43 UTC, dominik-zeglen approved these changes

2021-07-09 08:17 UTC, jwm0 approved these changes

2021-07-12 08:24 UTC, eCzerniak approved these changes

2021-07-12 08:34 UTC, merged