Add variant create options dialog
mirumee/saleor-dashboard pull request #1238
Opened 2021-07-16 16:51 UTC by orzechdev

I want to merge this change because... it adds a dialog to provide the ability to skip the variant creator.

**PR intended to be tested with API branch:** 

### Screenshots

Dialog displayed when trying to create first variants for product:

<img width="516" alt="Zrzut ekranu 2021-07-16 o 17 49 52" src="https://user-images.githubusercontent.com/9825562/125982010-8ce29c1b-b56c-493f-9669-eeb34f477b34.png">

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://qa.staging.saleor.cloud/graphql/

2021-07-16 16:51 UTC, patrys commented
Task linked: [SALEOR-3732 The ability to skip the variant creator](https://app.clickup.com/t/2549495/SALEOR-3732)

2021-07-19 08:04 UTC, pwgryglak approved these changes
looks fine

2021-07-19 14:47 UTC, jwm0 approved these changes

2021-07-20 10:03 UTC, mmarkusik requested changes

2021-07-20 10:03 UTC, mmarkusik commented on src/products/components/ProductVariantCreateDialog/ProductVariantCreateDialog.tsx
> +              <FormattedMessage
Extract all the messages to messages file

2021-07-22 09:07 UTC, mmarkusik approved these changes

2021-07-22 09:42 UTC, eCzerniak approved these changes

2021-07-22 09:56 UTC, merged