Add gift card update view #1 - Details Card
mirumee/saleor-dashboard pull request #1254
Opened 2021-07-22 11:44 UTC by mmarkusik

I want to merge this change because it adds gift card update view with details card. More details and other added stuff:
- Minor change: add isDarkTheme helper to avoid rewriting `themeType === "dark"` every time
- Major change: change money component as agreed with @pwgryglak to always show `USD 15.00` instead of `$ 15.00`
- Add vertical spacer component, similar to horizontal spacer
- Move order details page title (thus far only one with status chip) to generic Page title with status chip
- Add gift card details provider
- Add gift card update form provider
- Add time period text select component
- Add option to use `mapEdgesToItems` with Node without `name` prop, since tag items only use tag field

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-07-22 11:44 UTC, patrys commented
Task linked: [SALEOR-3912 Add Gift Card update view header, basic details & metadata fields](https://app.clickup.com/t/2549495/SALEOR-3912)

2021-07-22 11:55 UTC, pwgryglak approved these changes

2021-07-23 10:33 UTC, orzechdev requested changes

2021-07-23 10:33 UTC, orzechdev commented on src/giftCards/GiftCardUpdatePage/GiftCardUpdateDetailsCard/GiftCardUpdateDetailsCard.tsx
> +          </Button>
Set balance and create app?

2021-07-23 10:33 UTC, orzechdev commented on src/giftCards/index.tsx
> +const GiftCardUpdate: React.FC<RouteComponentProps<any>> = ({ match }) => (
Can we replace `any` with more specific type?

2021-07-23 14:42 UTC, orzechdev approved these changes

2021-07-23 14:43 UTC, merged