Add gift card update view #2
mirumee/saleor-dashboard pull request #1257
Opened 2021-07-23 14:58 UTC by mmarkusik

I want to merge this change because it adds info card to gift card details page, as well as some fixes and refactor

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-07-23 14:58 UTC, patrys commented
Task linked: [SALEOR-3912 Add Gift Card update view header, basic details & metadata fields](https://app.clickup.com/t/2549495/SALEOR-3912)

2021-07-26 07:27 UTC, jwm0 requested changes

2021-07-26 07:27 UTC, jwm0 commented on src/misc.ts
> +  return `${data.firstName} ${data.lastName}`;
You're not checking if `firstName` and `lastName` are undefined. The result of this function could be "undefined undefined"

2021-07-26 07:27 UTC, jwm0 commented on src/giftCards/GiftCardUpdatePage/GiftCardUpdateDetailsCard/GiftCardUpdateInfoCard.tsx
> +          <Typography>{usedByEmail || PLACEHOLDER}</Typography>
Extend `getStringOrPlaceholder` function to take a second `placeholder` argument and use it here

2021-07-26 07:27 UTC, jwm0 commented on src/giftCards/GiftCardUpdatePage/GiftCardUpdateDetailsCard/TimePeriodField.tsx
> +  typeFieldName: keyof T;
What's the use of generic typ here? What is T, you never define the original object. `string` seems more fitting

2021-07-26 09:39 UTC, orzechdev approved these changes

2021-07-27 10:20 UTC, jwm0 approved these changes

2021-07-27 10:20 UTC, merged