Hide no-stocks columns in fulfillment view
mirumee/saleor-dashboard pull request #1260
Opened 2021-07-26 15:44 UTC by orzechdev

I want to merge this change because... it hides no-stocks columns in fulfillment view.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-07-26 15:44 UTC, patrys commented
Task linked: [SALEOR-3853 Hide "No stocks" columns in fulfillment view](https://app.clickup.com/t/2549495/SALEOR-3853)

2021-07-26 15:59 UTC, pwgryglak approved these changes

2021-07-27 07:30 UTC, jwm0 requested changes

2021-07-27 07:30 UTC, jwm0 commented on src/orders/utils/data.ts
> +export function getOrderWarehouses(order: OrderFulfillData_order) {
Mark required parameters for this function to work properly and extend over it. At the moment it's too bounded to specific query data. `T extends { ... }` would be more appropriate

2021-07-27 08:31 UTC, mmarkusik approved these changes

2021-07-27 08:31 UTC, mmarkusik commented on src/orders/utils/data.ts
> +          warehouses.every(warehouse => warehouse.id !== stock.warehouse.id)
`every(getById(stock.warehouseId))`

2021-07-27 11:06 UTC, jwm0 approved these changes

2021-07-27 13:07 UTC, karola312 approved these changes

2021-07-28 07:44 UTC, merged