fix crash when deleting more than 21 vouchers
mirumee/saleor-dashboard pull request #1263
Opened 2021-07-27 14:57 UTC by SektorDV

I want to merge this change because it resolves the issue of the dashboard crashing when more than 21 vouchers are selected for deletion.

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-07-27 14:57 UTC, patrys commented
Task linked: [SALEOR-3967 Dashboard error on removing multiple vouchers](https://app.clickup.com/t/2549495/SALEOR-3967)

2021-07-28 08:20 UTC, orzechdev approved these changes
Maybe it's also worth to see if there are similar places in dashboard where same situation may occur, besides vouchers?

2021-07-28 09:41 UTC, jwm0 requested changes

2021-07-28 09:41 UTC, jwm0 commented on src/discounts/index.tsx
> +  const qs = parseQs(location.search.substr(1), { arrayLimit: Infinity });
Document why you need to do it this way, it looks confusing. Doesn't it also touch other parts of the app?

2021-08-04 10:11 UTC, SektorDV commented
turns out the problem was related to the way the application creates URL query strings (a number of places in the app used stringifyQs imported directly from the qs library rather than the one in utils). as a result, i removed the previous fix and globally replaced the stringifyQs imports across the app, which resolves the issue with vouchers and hopefully prevents similar issues from arising anywhere else. i checked the app for possible issues arising from the changes, but a doublecheck by QA probably couldn't hurt.

2021-08-05 09:31 UTC, jwm0 approved these changes
@SektorDV Please mention all the views that this change touches so QA can check each one of them

2021-08-09 10:07 UTC, merged