Extending dashboard
mirumee/saleor-dashboard pull request #1292
Opened 2021-08-13 14:17 UTC by jwm0

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-08-19 08:08 UTC, dominik-zeglen requested changes

2021-08-19 08:08 UTC, dominik-zeglen commented on src/components/ButtonWithSelect/ButtonWithSelect.tsx
> +              <ClickAwayListener onClickAway={handleClose}>
`@material-ui/core/Menu` doesn't meet requirements?

2021-08-19 08:08 UTC, dominik-zeglen commented on src/products/components/ProductListPage/ProductListPage.tsx
> +  }));
Helper map function?

2021-08-19 08:08 UTC, dominik-zeglen commented on src/products/components/ProductUpdatePage/ProductUpdatePage.tsx
> +  }));
Same as above

2021-08-19 08:08 UTC, dominik-zeglen commented on src/apps/components/AppDialog/AppDialog.tsx
> +  onClose(): void;
Let's be consistent with the rest of the project

```suggestion
  onClose: () => void;
```

2021-08-19 09:07 UTC, orzechdev approved these changes

2021-08-19 10:30 UTC, jwm0 commented on src/apps/components/AppFrame/useAppActions.ts
> +  };
Moving it to another file means also moving in all the outside depedencies (like `navigate` which comes from hook), I see your point but I'd wait before this gets big enough and then try to move it outside.

2021-08-19 13:01 UTC, jwm0 commented on src/components/ButtonWithSelect/ButtonWithSelect.tsx
> +              <ClickAwayListener onClickAway={handleClose}>
Menu doesn't have a placement prop

2021-08-20 07:22 UTC, dominik-zeglen approved these changes

2021-08-20 13:58 UTC, merged