[Saleor 3092] Swatch attributes
mirumee/saleor-dashboard pull request #1301
Opened 2021-08-17 17:50 UTC by piotrgrundas

I want to merge this change because it adds swatch attributes.

[Saleor PR](https://github.com/mirumee/saleor/pull/7261)

**PR intended to be tested with API branch:** 

### Screenshots
![image](https://user-images.githubusercontent.com/5078402/129775883-e39861fd-4648-4bf6-af2c-f4fb916262c5.png)
![image](https://user-images.githubusercontent.com/5078402/129775931-acec2d12-8b72-4061-a0cb-2d5ffa45a65a.png)

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-08-17 17:50 UTC, patrys commented
Task linked: [SALEOR-3092 Swatch attributes](https://app.clickup.com/t/2549495/SALEOR-3092)

2021-09-09 22:00 UTC, piotrgrundas commented on src/attributes/components/AttributePage/AttributePage.tsx
> +  children: (data: AttributePageFormData) => React.ReactNode;
I need it to have info about selected attr inputType at creation 👀

2021-09-13 11:35 UTC, bmigirl requested changes

2021-09-13 12:09 UTC, piotrgrundas commented on src/attributes/components/AttributeSwatchField/messages.ts
> +export const defined = defineMessages({
Why do u review outdated code? 🤔

2021-09-13 15:42 UTC, orzechdev requested changes

2021-09-13 15:42 UTC, orzechdev commented on src/attributes/components/AttributeSwatchField/AttributeSwatchField.tsx
> +            value: "image"
According to convention, move messages to `./messages.ts`

2021-09-13 15:42 UTC, orzechdev commented on src/attributes/components/AttributeValueEditDialog/AttributeValueEditDialog.tsx
> +        })
To make it more readable, maybe make it like:
```ts
const attributeValueFields = attributeValue?.fileUrl
      ? {
          fileUrl: attributeValue?.fileUrl,
          contentType: attributeValue?.contentType
        }
      : {
          value: attributeValue?.value ?? ""
        }

const initialForm: AttributeValueEditDialogFormData = {
  name: attributeValue?.name ?? "",
  ...attributeValueFields,
}

```

2021-09-13 15:42 UTC, orzechdev commented on src/attributes/utils/data.ts
> +      ...(fileUrl ? { fileUrl, contentType } : { value })
Same here, what do you think about making util for it e.g. `getAttributeValueTypeFields(attributeValue)`?

2021-09-13 20:58 UTC, piotrgrundas commented on src/attributes/components/AttributeSwatchField/AttributeSwatchField.tsx
> +    set({ value: hex, fileUrl: undefined, contentType: undefined });
API type.

2021-09-13 21:01 UTC, piotrgrundas commented on src/attributes/components/AttributeValues/AttributeValues.tsx
> +                <FormattedMessage
Not one message, nor style has a separate file here 🙄 ...

2021-09-14 08:46 UTC, orzechdev approved these changes

2021-09-15 07:24 UTC, pwgryglak approved these changes

2021-09-15 08:09 UTC, bmigirl approved these changes

2021-09-21 08:00 UTC, pwgryglak approved these changes

2021-09-21 12:29 UTC, eCzerniak approved these changes

2021-09-21 13:16 UTC, merged