disable button when no items selected
mirumee/saleor-dashboard pull request #1304
Opened 2021-08-18 13:44 UTC by SektorDV

I want to merge this change because it fixes the issue of the confirm button being enabled when no items have been selected in the shipping dialog.

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-08-18 13:44 UTC, patrys commented
Task linked: [SALEOR-2984 An error is shown after confirming an empty selection of shipping method on Orders.](https://app.clickup.com/t/2549495/SALEOR-2984)

2021-08-19 10:04 UTC, orzechdev approved these changes

2021-08-20 07:20 UTC, eCzerniak approved these changes

2021-08-20 08:05 UTC, jwm0 requested changes
Code looks good but this PR should first be merged into `3.0`

2021-08-23 09:14 UTC, jwm0 approved these changes

2021-08-23 09:16 UTC, merged