horizontal scroll fix
mirumee/saleor-dashboard pull request #1306
Opened 2021-08-19 10:41 UTC by SektorDV

I want to merge this change because it fixes the issue with overflows being hidden in responsive tables.

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-08-19 10:41 UTC, patrys commented
Task linked: [SALEOR-4129 Add validation to not allow creating gift card with 0 balance amount](https://app.clickup.com/t/2549495/SALEOR-4129)

2021-08-19 14:11 UTC, orzechdev approved these changes

2021-08-20 07:25 UTC, jwm0 requested changes
You're using lockfileVrsion 2 (npm v7) which generates a huge package-lock diff. Also, please rebase to newest 3.0 and make sure all jobs in CI pass

2021-08-20 10:57 UTC, jwm0 approved these changes

2021-08-20 11:06 UTC, patrys commented
Task linked: [SALEOR-4219 Tables do not support horizontal scroll](https://app.clickup.com/t/2549495/SALEOR-4219)

2021-08-20 11:18 UTC, merged