Saleor 4033 tests for plugins
mirumee/saleor-dashboard pull request #1317
Opened 2021-08-23 12:04 UTC by karola312

I want to merge this change because I created tests for plugins

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-08-23 12:04 UTC, patrys commented
Task linked: [SALEOR-4033 Create tests for plugins](https://app.clickup.com/t/2549495/SALEOR-4033)

2021-09-02 08:06 UTC, dominik-zeglen commented on cypress/apiRequests/Customer.js
> +  const mutation = `mutation{
I'm wondering if there's a way to improve this and use `gql` tag

2021-09-02 08:07 UTC, dominik-zeglen approved these changes

2021-09-06 12:21 UTC, eCzerniak approved these changes

2021-09-07 07:40 UTC, jwm0 requested changes
After you've finished you should run `npm run test -- -u` to update snapshots (changes to `date-test-id`)

2021-09-07 07:40 UTC, jwm0 commented on src/plugins/components/PluginDetailsChannelsCard/PluginDetailsChannelsCardContent.tsx
> +            data-tes-id="channel"
```suggestion
            data-test-id="channel"
```

2021-09-07 07:40 UTC, jwm0 commented on src/plugins/components/PluginsList/PluginsList.tsx
> +                data-test="id"
test-id should be more precise
```suggestion
                data-test-id="plugin"
```

2021-09-10 08:11 UTC, jwm0 approved these changes

2021-09-10 09:03 UTC, merged