Saleor 2993
mirumee/saleor-dashboard pull request #1321
Opened 2021-08-24 10:39 UTC by mstrumeck

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-08-24 10:39 UTC, patrys commented
Task linked: [SALEOR-2993 Product variant channel listing webhooks (stocks)](https://app.clickup.com/t/2549495/SALEOR-2993)

2021-08-24 13:37 UTC, jwm0 requested changes
Update schema (the one from branch) and rerun type generation:
```
npm run build-types
```

2021-08-24 14:47 UTC, SektorDV approved these changes

2021-08-25 07:51 UTC, jwm0 approved these changes

2021-09-03 11:36 UTC, merged