Modify order return page to show quantityToFulfill
mirumee/saleor-dashboard pull request #1349
Opened 2021-08-31 14:21 UTC by tomaszszymanski129

I want to merge this change because order return page used to show (for unfulfilled items) quantity - quantity fulfilled. It should utilize new backend order line property - quantityToFulfill instead.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-08-31 14:21 UTC, patrys commented
Task linked: [SALEOR-4305 "waiting" fulfillments are incorrectly handled on return page](https://app.clickup.com/t/2549495/SALEOR-4305)

2021-09-07 10:04 UTC, jwm0 requested changes

2021-09-08 07:14 UTC, dominik-zeglen approved these changes

2021-09-09 07:33 UTC, jwm0 approved these changes

2021-09-09 10:52 UTC, eCzerniak approved these changes

2021-09-09 10:59 UTC, merged