Saleor 4387/draft order incorrect label
mirumee/saleor-dashboard pull request #1375
Opened 2021-09-09 09:21 UTC by Droniu

I want to merge this change because I fixed the incorrect label in order drafts.

**PR intended to be tested with API branch:** 

### Screenshots
before:
![image](https://user-images.githubusercontent.com/41952692/132657962-93176b38-6fe0-420c-93b0-dc97239782c1.png)

after:
![image](https://user-images.githubusercontent.com/41952692/132657773-9b1cbe54-adff-464c-af29-add786b8f872.png)

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [x] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-09-09 09:21 UTC, patrys commented
Task linked: [SALEOR-4387 Incorrect label in Dashboard draft order](https://app.clickup.com/t/2549495/SALEOR-4387)

2021-09-09 09:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mirumee/saleor-dashboard?pullRequest=1375) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mirumee/saleor-dashboard?pullRequest=1375) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mirumee/saleor-dashboard?pullRequest=1375) it.</sub>

2021-09-09 10:26 UTC, jwm0 approved these changes

2021-09-09 15:57 UTC, mmarkusik approved these changes

2021-09-09 15:57 UTC, mmarkusik commented on src/orders/components/OrderDraftDetailsSummary/OrderDraftDetailsSummary.tsx
> +  addShippingAddressInfo: {
Since we decided to use local messages files for messages it'd be a good moment to move it? :)

2021-09-10 10:34 UTC, jwm0 requested changes

2021-09-10 10:34 UTC, jwm0 commented on src/orders/components/OrderDraftDetailsSummary/messages.ts
> +export default defineMessages({
Use named exports over default ones:
```suggestion
export const messages = defineMessages({
```

2021-09-10 10:59 UTC, Droniu commented on src/orders/components/OrderDraftDetailsSummary/OrderDraftDetailsSummary.tsx
> +import messages from "./messages";
```suggestion
import { messages } from "./messages";
```

2021-09-10 12:19 UTC, jwm0 approved these changes

2021-09-10 12:22 UTC, bmigirl approved these changes

2021-09-13 09:13 UTC, merged