Fix sidebar navigation and Products Page overlapping problem
mirumee/saleor-dashboard pull request #1382
Opened 2021-09-13 09:13 UTC by kamilpastuszka

This PR is to fix content overlapping issue between sidebar navigation and Products Page.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-09-13 09:13 UTC, patrys commented
Task linked: [SALEOR-4412 Sidebar navigation and Products Page overlapping problem](https://app.clickup.com/t/2549495/SALEOR-4412)

2021-09-13 14:59 UTC, orzechdev requested changes

2021-09-13 14:59 UTC, orzechdev commented on src/products/components/ProductListPage/ProductListPage.tsx
> +        marginLeft: "211px"
Use `drawerWidthExpanded` from `@saleor/components/AppLayout/consts`

2021-09-14 09:28 UTC, bmigirl commented on src/products/components/ProductListPage/ProductListPage.tsx
> +        marginLeft: "211px"
What he said ☝️

2021-09-14 11:10 UTC, kamilpastuszka commented on src/products/components/ProductListPage/ProductListPage.tsx
> +        marginLeft: "211px"
done

2021-09-14 14:57 UTC, orzechdev approved these changes

2021-09-15 08:29 UTC, bmigirl commented
There's still this one case where the table itself overlaps, I think it could be full page width at this point. @pwgryglak wdyt?
<img width="1289" alt="Screenshot 2021-09-15 at 10 23 44" src="https://user-images.githubusercontent.com/28022710/133397906-203369d3-5744-4021-b190-ecc1370b3552.png">

2021-09-16 08:43 UTC, pwgryglak commented
> There's still this one case where the table itself overlaps, I think it could be full page width at this point. @pwgryglak wdyt?
> <img alt="Screenshot 2021-09-15 at 10 23 44" width="1289" src="https://user-images.githubusercontent.com/28022710/133397906-203369d3-5744-4021-b190-ecc1370b3552.png">

2021-09-16 10:01 UTC, kamilpastuszka commented
@bmigirl What breakpoint was it?
Overlapping text in the table is fixed in a different PR.

2021-09-17 08:39 UTC, bmigirl commented
@kamilpastuszka I didn't check, so please do

2021-09-20 08:45 UTC, kamilpastuszka commented
@bmigirl Could you check again? It seems don’t have that issue.

2021-09-21 13:15 UTC, bmigirl commented
@kamilpastuszka still happening in the deployment
<img width="596" alt="Screenshot 2021-09-21 at 15 15 21" src="https://user-images.githubusercontent.com/28022710/134177124-5f9133eb-04ef-4fd4-bfc5-ea868f46f980.png">

2021-09-22 07:13 UTC, kamilpastuszka commented
@bmigirl Can you confirm the breakpoint?

2021-09-23 12:08 UTC, bmigirl commented
@kamilpastuszka do you need instruction on how to debug this?

2021-09-23 14:42 UTC, kamilpastuszka commented
@bmigirl In order to verify it correctly I need to make sure we are looking at the same screen size. This is why I asked you to confirm the breakpoint/screen width.

2021-09-24 09:32 UTC, bmigirl commented
@kamilpastuszka `lg`

2021-09-24 11:33 UTC, kamilpastuszka commented
This is how it looks at Material UI lg breakpoint. Here 1200px.

![products-lg-breakpoint](https://user-images.githubusercontent.com/33246308/134667291-8bff1512-a6c8-4983-a3fa-2a998747d8d2.png)

2021-09-27 08:11 UTC, jwm0 approved these changes

2021-09-27 11:34 UTC, bmigirl approved these changes

2021-10-06 09:25 UTC, merged