Fix wrong words and ordering for staff member form
mirumee/saleor-dashboard pull request #1424
Opened 2021-09-21 11:25 UTC by kamilpastuszka

I want to merge this to fix wrong words and ordering for staff member form.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-09-21 11:25 UTC, patrys commented
Task linked: [SALEOR-2147 Wrong Description/Title/Ordering in Staff Member Form](https://app.clickup.com/t/2549495/SALEOR-2147)

2021-09-21 11:42 UTC, krzysztofwolski requested changes

2021-09-21 11:42 UTC, krzysztofwolski commented on src/staff/components/UserStatus/UserStatus.tsx
> +  //
:police_car:

2021-09-22 09:44 UTC, bmigirl requested changes

2021-09-22 09:44 UTC, bmigirl commented on src/staff/components/StaffDetailsPage/StaffDetailsPage.tsx
> +                        defaultMessage: "User is active",
Move to local messages file

2021-09-22 09:44 UTC, bmigirl commented on src/staff/components/UserStatus/UserStatus.tsx
> +          defaultMessage: "User Status",
Same as above

2021-09-22 09:44 UTC, bmigirl commented on src/staff/components/UserStatus/UserStatus.tsx
> +          <FormattedMessage defaultMessage="If you want to disable this User please uncheck the box below." />
Same as above

2021-09-23 09:14 UTC, krzysztofwolski approved these changes

2021-09-24 10:22 UTC, bmigirl requested changes

2021-09-24 10:22 UTC, bmigirl commented on src/intl.ts
> +  userStatus: {
These messages should be in local messages file, not it the main / common messages.

2021-09-30 07:35 UTC, bmigirl approved these changes

2021-10-06 09:21 UTC, merged