Refactor Translations Page
mirumee/saleor-dashboard pull request #1451
Opened 2021-09-29 13:48 UTC by kamilpastuszka

This PR is to refactor Translations Page as per ticket description.

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] This code contains UI changes
2. [ ] All visible strings are translated with proper context including data-formatting
3. [ ] Attributes `[data-test-id]` are added for new elements
4. [ ] Changes are mentioned in the changelog
5. [ ] The changes are tested in different browsers and in light/dark mode

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-09-29 13:48 UTC, patrys commented
Task linked: [SALEOR-4439 Refactor page translations](https://app.clickup.com/t/2549495/SALEOR-4439)

2021-09-29 14:07 UTC, jwm0 requested changes

2021-09-29 14:07 UTC, jwm0 commented on src/translations/utils.ts
> +export const getTranslationFields = (fields, intl) =>
Add TS types

2021-09-29 14:35 UTC, bmigirl requested changes

2021-09-29 14:35 UTC, bmigirl commented on src/translations/components/TranslationsAttributesPage/messages.ts
> +const messages = defineMessages({
Should be a named export `transtionsAttributesPageFieldsMessages` and in the file imported 
```
import { transtionsAttributesPageFieldsMessages as messages } from 'messages'

2021-09-30 07:28 UTC, bmigirl approved these changes

2021-10-04 08:24 UTC, jwm0 approved these changes

2021-10-06 09:19 UTC, merged