WIP refactor of login tests
mirumee/saleor-dashboard pull request #630
Opened 2020-07-30 13:27 UTC by michalina-graczyk

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-08-17 14:08 UTC, michalina-graczyk commented
Not working because of https://app.clickup.com/t/7cw0fe

2020-08-20 08:02 UTC, krzysztofwolski requested changes

2020-08-20 08:02 UTC, krzysztofwolski commented on cypress/integration/warehouse.js
> +      // .get("[data-testid=defaultwarehouse]")
Remove unused code

2020-08-20 08:05 UTC, michalina-graczyk commented on cypress/integration/warehouse.js
> +      // .get("[data-testid=defaultwarehouse]")
good catch!

2020-08-20 09:15 UTC, dominik-zeglen approved these changes

2020-08-20 10:42 UTC, AlicjaSzu approved these changes

2020-08-20 13:36 UTC, merged