update VisibilityCard component
mirumee/saleor-dashboard pull request #679
Opened 2020-08-26 10:22 UTC by AlicjaSzu

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-08-26 10:24 UTC, patrys commented
Task linked: [CU-7epck0 Dashboard changes for "visible in listings" feature](https://app.clickup.com/t/7epck0)

2020-08-31 09:03 UTC, orzechdev approved these changes

2020-08-31 11:40 UTC, dominik-zeglen requested changes
Styling is a little bit off. 

<img width="307" alt="Screenshot 2020-08-31 at 12 50 12" src="https://user-images.githubusercontent.com/6833443/91712685-8d7bc580-eb88-11ea-80ca-951ed0e59a3b.png">

2020-08-31 11:40 UTC, dominik-zeglen commented on src/components/VisibilityCard/VisibilityCard.tsx
> +    visibleInListings?: boolean;
I get a feeling that we should create new component that would be embedding `VisibilityCard` passing additional elements as props

2020-08-31 11:40 UTC, dominik-zeglen commented on src/components/VisibilityCard/VisibilityCard.tsx
> +                  defaultMessage: "Published"
I think this should be passed as prop because it's missing a context.
"Opublikowany" lub "Opublikowana" in polish makes difference

2020-08-31 11:40 UTC, dominik-zeglen commented on src/components/VisibilityCard/VisibilityCard.tsx
> +                  defaultMessage: "Not published"
Same as above

2020-08-31 11:40 UTC, dominik-zeglen commented on src/components/VisibilityCard/VisibilityCard.tsx
> +                        description: "publication date"
Same as above

2020-08-31 11:40 UTC, dominik-zeglen commented on src/components/VisibilityCard/VisibilityCard.tsx
> +                      description: "available on date"
Maybe pass an object with messages?
A lot of them depend on a context 🤷‍♂️

2020-09-01 09:33 UTC, maarcingebala commented
As @dominik-zeglen mentioned there are small styling differences between the screenshot and designs:
- "Set availability date" and "Set publication date" shouldn't have any underline 
- "Will become available on" and "Since <date>" text have different styles - grey color and smaller line spacing
- "Disabling this checkbox will remove product ..." - this text is also using a different styling - grey text and smaller line spacing

2020-09-02 16:55 UTC, dominik-zeglen approved these changes

2020-09-03 10:25 UTC, merged