Add metadata editor to creator views
mirumee/saleor-dashboard pull request #684
Opened 2020-09-01 15:10 UTC by dominik-zeglen

I want to merge this change because it adds metadata editor to creator views.

**PR intended to be tested with API branch:** master

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [x] Number of API calls is optimized.
1. [x] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-09-01 16:30 UTC, patrys commented
Task linked: [CU-7mreaz Add metadata editor to creator views](https://app.clickup.com/t/7mreaz)

2020-09-01 17:00 UTC, krzysztofwolski approved these changes

2020-09-01 17:08 UTC, orzechdev requested changes

2020-09-02 10:11 UTC, dominik-zeglen commented on src/attributes/components/AttributePage/AttributePage.tsx
>        : undefined;
At first I thought it isn't the same, but I made table of truth and it should work, nice

2020-09-02 15:32 UTC, orzechdev approved these changes

2020-09-02 16:54 UTC, merged