variant optional attributes
mirumee/saleor-dashboard pull request #693
Opened 2020-09-04 10:00 UTC by AlicjaSzu

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-09-07 09:44 UTC, patrys commented
Task linked: [CU-7jw8ef Dashboard optional variant attributes changes](https://app.clickup.com/t/7jw8ef)

2020-09-07 13:55 UTC, orzechdev approved these changes

2020-09-07 13:55 UTC, orzechdev commented on src/products/components/ProductVariantCreatorPage/ProductVariantChooseAttributes.tsx
> +                  checked={selected === 0 ? false : true}
```suggestion
                  checked={selected !== 0}
```

2020-09-09 08:35 UTC, krzysztofwolski approved these changes

2020-09-09 08:37 UTC, maarcingebala commented
Please don't merge this one yet. The feature was not fully refined and we need to check if this can be merged in this shape.

2020-09-10 11:48 UTC, dominik-zeglen requested changes
<img width="870" alt="Screenshot 2020-09-10 at 13 47 42" src="https://user-images.githubusercontent.com/6833443/92725331-49e54080-f36c-11ea-83c2-f88ced2fae30.png">
<img width="760" alt="Screenshot 2020-09-10 at 13 47 56" src="https://user-images.githubusercontent.com/6833443/92725340-4baf0400-f36c-11ea-9d0e-d205e643d957.png">

Doesn't look the same

2020-09-21 15:44 UTC, dominik-zeglen requested changes
A few things are missing or need fixing:
- [ ] variant creator has "choose attributes" section, but it doesn't have corresponding story
- [ ] interactive story does not work as it's supposed to; if I select "author" and "color", in second view I get to choose "box size" and "coffee genre" 
- [ ] variant creator should not be able to proceed if no attributes were chosen
- [ ] missing tests (`createVariants.test.ts`, `reducer.test.ts`)
- [ ] styles exploded <img width="867" alt="Screenshot 2020-09-21 at 13 26 20" src="https://user-images.githubusercontent.com/6833443/93761476-21800080-fc0e-11ea-80e4-5b5943d9c7d6.png">

2020-11-18 14:39 UTC, krzysztofwolski commented
Blocked #6059

2021-03-26 09:16 UTC, maarcingebala commented
Closing this for now, we need to rethink the requirements for this feature and get back to it in the future.

2021-03-26 09:16 UTC, closed without merging