Restyle side menu
mirumee/saleor-dashboard pull request #697
Opened 2020-09-07 15:55 UTC by dominik-zeglen

I want to merge this change because it implements new sidebar design.

**PR intended to be tested with API branch:** master

### Screenshots
<img width="1680" alt="Screenshot 2020-09-07 at 17 52 02" src="https://user-images.githubusercontent.com/6833443/92404144-297e7180-f133-11ea-9670-36c52260bf6c.png">
<img width="1680" alt="Screenshot 2020-09-07 at 17 52 20" src="https://user-images.githubusercontent.com/6833443/92404152-2c796200-f133-11ea-8ea2-33cd4318c2c1.png">
<img width="1680" alt="Screenshot 2020-09-07 at 17 52 39" src="https://user-images.githubusercontent.com/6833443/92404155-2d11f880-f133-11ea-98e5-032e503f0731.png">

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [x] The changes are tested.
1. [x] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-09-07 16:01 UTC, patrys commented
Task linked: [CU-7utb1g Rewrite sidebar menu](https://app.clickup.com/t/7utb1g)

2020-09-08 09:10 UTC, AlicjaSzu approved these changes

2020-09-08 10:02 UTC, orzechdev requested changes
1. When I open submenu, I'm getting:
![Zrzut ekranu 2020-09-8 o 11 46 19](https://user-images.githubusercontent.com/9825562/92460991-f71f5380-f1c8-11ea-86f4-9732e14071d7.png)
2. When I go to categories and open submenu, under which is search bar, I cannot click on submenu item, instead I am only able to activate search bar:
<img width="297" alt="Zrzut ekranu 2020-09-8 o 12 01 13" src="https://user-images.githubusercontent.com/9825562/92462629-030c1500-f1cb-11ea-9463-f91f68eff90d.png">

2020-09-08 10:25 UTC, dominik-zeglen commented on src/components/SideBar/utils.ts
> +}
Mindlessly copied some code, but yeah, it looks way nicer

2020-09-08 11:11 UTC, dominik-zeglen commented
All fixed 👌

2020-09-08 14:34 UTC, orzechdev approved these changes

2020-09-09 08:22 UTC, krzysztofwolski approved these changes

2020-09-09 08:25 UTC, krzysztofwolski requested changes
![image](https://user-images.githubusercontent.com/5188636/92573875-ac641100-f286-11ea-878f-ac045c0c56a8.png)
Hamburger icon appears. Seems to be leftover component.

2020-09-09 08:26 UTC, dominik-zeglen commented
Mobile version will be added in another PR @krzysztofwolski

2020-09-09 08:36 UTC, krzysztofwolski approved these changes

2020-09-10 14:19 UTC, merged