channels modal - new styles, search input
mirumee/saleor-dashboard pull request #717
Opened 2020-09-17 16:56 UTC by AlicjaSzu

I want to merge this change because...

**PR intended to be tested with API branch:** feature/multichannel-multicurrency

### Screenshots
<img width="897" alt="Screenshot 2020-09-18 at 13 56 56" src="https://user-images.githubusercontent.com/10812388/93594820-dcae5c80-f9b6-11ea-93b1-b69d04d5ae5d.png">

### Pull Request Checklist

1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Translated strings are extracted.
1. [x] Number of API calls is optimized.
1. [x] The changes are tested.
1. [x] Data-test are added for new elements.
1. [x] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-09-17 16:57 UTC, patrys commented
Task linked: [SALEOR-1010 update channels modal](https://app.clickup.com/t/2549495/SALEOR-1010)

2020-09-18 12:38 UTC, krzysztofwolski approved these changes

2020-09-18 13:36 UTC, orzechdev requested changes

2020-09-18 13:36 UTC, orzechdev commented on src/products/views/ProductUpdate/ProductUpdate.tsx
> +    }
```suggestion
    if (selected !== items.length) {
      setChannels(items);
    } else {
      setChannels([]);
    }
```

2020-09-21 10:23 UTC, merged