update variant creator
mirumee/saleor-dashboard pull request #724
Opened 2020-09-21 20:31 UTC by AlicjaSzu

I want to merge this change because...

**PR intended to be tested with API branch:** feature/multichannel-multicurrency

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-09-21 20:34 UTC, patrys commented
Task linked: [SALEOR-895 Update variant creator](https://app.clickup.com/t/2549495/SALEOR-895)

2020-09-24 09:22 UTC, krzysztofwolski requested changes

2020-09-24 09:22 UTC, krzysztofwolski commented on src/components/PriceField/PriceField.tsx
> +  const hasWrongValue = value < 0;
```suggestion
  const minValue = 0;
```

2020-09-24 09:22 UTC, krzysztofwolski commented on src/components/PriceField/PriceField.tsx
> +        min: 0,
```suggestion
        min: minValue,
```

2020-09-24 09:22 UTC, krzysztofwolski commented on src/components/PriceField/PriceField.tsx
> +        ) : hasWrongValue ? (
```suggestion
        ) : value < minValue ? (
```

2020-09-24 09:22 UTC, krzysztofwolski commented on src/products/components/ProductVariantCreatorPage/ProductVariantCreatorPage.tsx
> +            channel => channel.price !== "" && parseInt(channel.price, 10) >= 0
Maybe creating util func for string price check would be good idea?

2020-09-24 09:22 UTC, krzysztofwolski commented on src/products/components/ProductVariantCreatorPage/ProductVariantCreatorPrices.tsx
> +                          <TextField
Can't we reuse PriceField here?

2020-09-24 09:22 UTC, krzysztofwolski commented on src/products/components/ProductVariantCreatorPage/reducer.ts
> +            value: [] // ""
Left intentionally?

2020-09-24 10:56 UTC, AlicjaSzu commented on src/products/components/ProductVariantCreatorPage/reducer.ts
> +            value: [] // ""
i forgot to remove

2020-09-25 13:15 UTC, orzechdev commented on src/products/components/ProductVariantPrice/ProductVariantPrice.tsx
> +                          hint={error?.length ? error[0].message : ""}
Where are these errors coming from? Shouldn't they have translations?

2020-09-28 11:22 UTC, dominik-zeglen requested changes

2020-09-29 09:47 UTC, AlicjaSzu commented on src/products/components/ProductVariantCreatorPage/ProductVariantCreatorSummary.tsx
> +                      }
no, it seems to work correctly

2020-09-29 15:43 UTC, dominik-zeglen approved these changes

2020-09-29 16:17 UTC, merged