Use regex instead of string to replace all "\n" occurences
mirumee/saleor-dashboard pull request #736
Opened 2020-09-29 14:21 UTC by dominik-zeglen

I want to merge this change because if message contains more than one `\n` symbols, only the first will be replaced, resulting in misformatted message.

**PR intended to be tested with API branch:** master

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-09-29 14:22 UTC, krzysztofwolski approved these changes

2020-09-29 16:15 UTC, orzechdev approved these changes

2020-09-30 14:26 UTC, AlicjaSzu approved these changes

2020-10-01 07:45 UTC, mmarkusik requested changes

2020-10-01 07:45 UTC, mmarkusik commented on src/components/Timeline/TimelineNote.tsx
> +              __html: message.replace(/\n/, "<br />")
Won't this replace only the first occurrence? 

``` 
"foobar \n pops \n".replace(/\n/, "<br />")
```
will do:
```
"foobar <br /> pops 
"
```

`replaceAll` ?

2020-10-02 08:14 UTC, mmarkusik approved these changes

2020-10-02 09:05 UTC, krzysztofwolski approved these changes

2020-10-02 09:05 UTC, merged