products/shipping/discount list settings
mirumee/saleor-dashboard pull request #739
Opened 2020-09-30 11:02 UTC by AlicjaSzu

I want to merge this change because...

**PR intended to be tested with API branch:** feature/multichannel-multicurrency

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-09-30 11:05 UTC, patrys commented
Task linked: [SALEOR-1113 Products/sales/vouchers/shipping list settings](https://app.clickup.com/t/2549495/SALEOR-1113)

2020-09-30 15:53 UTC, orzechdev requested changes
When I don't have any channel created, I'm still getting dialog opened when opening the product list page:
![Zrzut ekranu 2020-09-30 o 17 35 23](https://user-images.githubusercontent.com/9825562/94707498-c653b980-0343-11eb-84ec-33e6813434f6.png)

2020-10-01 11:49 UTC, orzechdev commented on src/discounts/views/SaleList/SaleList.tsx
> +    : {};
I think it is easier to read:
```suggestion
  const onSettingsOpen = !!channelChoices.length
    ? () => openModal("settings")
    : undefined;
```

2020-10-01 11:49 UTC, orzechdev commented on src/discounts/views/SaleList/SaleList.tsx
> +              {...onSettingsOpen}
Or even:
```suggestion
              onSettingsOpen={!!channelChoices.length ?
                  () => openModal("settings")} :
                  undefined
```

2020-10-02 08:13 UTC, orzechdev approved these changes

2020-10-02 08:38 UTC, merged