Prevent negative price setting in input
mirumee/saleor-dashboard pull request #747
Opened 2020-10-05 16:21 UTC by orzechdev

I want to merge this change because...

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-10-06 08:51 UTC, patrys commented
Task linked: [SALEOR-1243 [Variants] User shouldn't be able to set value below zero using button](https://app.clickup.com/t/2549495/SALEOR-1243)

2020-10-07 08:56 UTC, AlicjaSzu approved these changes

2020-10-09 08:31 UTC, dominik-zeglen requested changes

2020-10-09 08:31 UTC, dominik-zeglen commented on src/products/components/ProductPricing/ProductPricing.tsx
> +    if (/^\d*(\.\d+)?$/.test(event.target.value)) {
As I mentioned it in #754, this should be util func

2020-10-09 11:47 UTC, dominik-zeglen approved these changes

2020-10-09 12:27 UTC, orzechdev commented
passed to QA

2020-10-12 14:54 UTC, mlamperski approved these changes
Tested positive

2020-10-12 15:02 UTC, merged