channels currency code select
mirumee/saleor-dashboard pull request #806
Opened 2020-10-29 18:39 UTC by AlicjaSzu

I want to merge this change because...

- adds select with currency codes in ChannelCreate view

**PR intended to be tested with API branch:** feature/multichannel-multicurrency

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://feature-multichannel-multicurrency.api.saleor.rocks/graphql/

2020-10-29 18:41 UTC, patrys commented
Task linked: [SALEOR-1486 [BUG] Channel currency does not work between upper and lower cases](https://app.clickup.com/t/2549495/SALEOR-1486)

2020-10-30 10:22 UTC, dominik-zeglen requested changes

2020-10-30 10:22 UTC, dominik-zeglen commented on src/channels/pages/ChannelDetailsPage/handlers.ts
> +export default createSingleAutocompleteSelectHandler;
I don't see any difference
`src/utils/handlers/singleAutocompleteSelectChangeHandler.ts`

2020-10-30 10:22 UTC, dominik-zeglen commented on src/channels/views/ChannelCreate/ChannelCreate.tsx
> +    label: `${currencyData.code} - ${currencyData.countries.join(",")}`,
Shouldn't it be translated somehow?

2020-10-30 12:28 UTC, orzechdev approved these changes

2020-10-30 12:34 UTC, mmarkusik approved these changes

2020-11-02 09:13 UTC, merged