Add page type configuration in page details page
mirumee/saleor-dashboard pull request #808
Opened 2020-10-30 12:21 UTC by orzechdev

I want to merge this change because... it adds:
- page type selection on page creation
- page attribute values selection based on the selected page type

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-10-30 12:22 UTC, patrys commented
Task linked: [SALEOR-1180 Add ability to assign page type on a page details page](https://app.clickup.com/t/2549495/SALEOR-1180)

2020-10-30 12:22 UTC, patrys commented
Task linked: [SALEOR-1183 Handle getting and saving attribute values on a page details view](https://app.clickup.com/t/2549495/SALEOR-1183)

2020-11-02 08:17 UTC, patrys commented
Task linked: [SALEOR-1460 Update attribute mutations permissions](https://app.clickup.com/t/2549495/SALEOR-1460)

2020-11-05 09:29 UTC, dominik-zeglen requested changes

2020-11-05 09:29 UTC, dominik-zeglen commented on src/pages/components/PageOrganizeContent/PageOrganizeContent.tsx
> +  onPageTypeChange?: (event: React.ChangeEvent<any>) => void;
onPageTypeChange?: FormChange;

2020-11-05 09:29 UTC, dominik-zeglen commented on src/pages/components/PageOrganizeContent/PageOrganizeContent.tsx
> +  onPageTypeChange?: (event: React.ChangeEvent<any>) => void;
```suggestion
  onPageTypeChange?: FormChange;
```

2020-11-05 09:29 UTC, dominik-zeglen commented on src/pages/components/PageOrganizeContent/PageOrganizeContent.tsx
> +            }
```suggestion
            choices={pageTypes ? mapNodeToChoice(pageTypes) : []}
```

2020-11-05 09:29 UTC, dominik-zeglen commented on src/pages/utils/handlers.ts
> +}
Can we test them? They are quite complex.

2020-11-06 09:37 UTC, dominik-zeglen approved these changes

2020-11-06 09:38 UTC, merged