Add file type attribute
mirumee/saleor-dashboard pull request #824
Opened 2020-11-09 11:57 UTC by orzechdev

I want to merge this change because... it adds file type attribute.

Note: needs to be updated, when backend implementation is ready.

**PR intended to be tested with API branch:** 

### Screenshots

<img width="1282" alt="Zrzut ekranu 2020-11-9 o 12 55 10" src="https://user-images.githubusercontent.com/9825562/98538324-da67d080-228a-11eb-8523-14df82b15e18.png">

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-11-09 12:00 UTC, patrys commented
Task linked: [SALEOR-1341 Adjust attribute details view](https://app.clickup.com/t/2549495/SALEOR-1341)

2020-11-19 08:57 UTC, mmarkusik approved these changes

2020-11-24 16:58 UTC, krzysztofwolski commented
Can't test this PR without rebasing to current master (Iooks like file uploads feature branch need rebase first)

2020-11-25 09:00 UTC, jwm0 requested changes

2020-11-25 09:00 UTC, jwm0 commented on src/attributes/components/AttributeProperties/AttributeProperties.tsx
> +              <FormSpacer />
If the condition below (`filterableInStorefront`) doesn't pass we'll have 2 FormSpacer components on top of each other, is this the intended behaviour?

2020-12-03 11:49 UTC, jwm0 approved these changes

2020-12-03 11:50 UTC, merged