Saleor 1612/add order confimation
mirumee/saleor-dashboard pull request #844
Opened 2020-11-20 09:35 UTC by mmarkusik

I want to merge this change because it adds order confirm feature to order details. Also adds order confirmed to order history. 

[TICKET](https://app.clickup.com/t/2549495/SALEOR-1612)

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-11-20 09:35 UTC, patrys commented
Task linked: [SALEOR-1612 Add possibility to confirm an order through dashboard](https://app.clickup.com/t/2549495/SALEOR-1612)

2020-11-23 09:40 UTC, orzechdev approved these changes

2020-11-23 13:40 UTC, dominik-zeglen requested changes

2020-11-23 13:40 UTC, dominik-zeglen commented on src/orders/components/OrderDetailsPage/OrderDetailsPage.tsx
> +      ? intl.formatMessage({ defaultMessage: "confirm order" })
Missing description

2020-11-23 13:40 UTC, dominik-zeglen commented on src/orders/components/OrderDetailsPage/OrderDetailsPage.tsx
> +  const getSaveLabel = () =>
I don't see the reason why this should be a function

2020-11-23 13:40 UTC, dominik-zeglen commented on src/orders/views/OrderDetails/index.tsx
> +                          }
Can we move this logic to submit handler and decide there whether order should be confirmed or not?

2020-11-23 16:25 UTC, krzysztofwolski approved these changes

2020-11-23 18:53 UTC, merged