Create channel picker for draft order creation
mirumee/saleor-dashboard pull request #849
Opened 2020-11-20 16:14 UTC by jwm0

To create a draft order we need to know its channel beforehand. This picker allows user to specify the channel explicitly while also defaulting to the currently selected global channel.

https://app.clickup.com/t/2549495/SALEOR-1611
**PR intended to be tested with API branch:** 

### Screenshots
![image](https://user-images.githubusercontent.com/28310983/99822666-cc9c3000-2b53-11eb-8b14-298d13de74da.png)

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-11-20 16:14 UTC, patrys commented
Task linked: [SALEOR-1611 Channel chooser when draft order create](https://app.clickup.com/t/2549495/SALEOR-1611)

2020-11-23 09:37 UTC, dominik-zeglen requested changes

2020-11-23 09:37 UTC, dominik-zeglen commented on src/orders/views/OrderDraftList/OrderDraftList.tsx
> +  );
To maintain consistency with the rest of the project I recommend using query params to open this dialog.

2020-11-23 10:58 UTC, orzechdev requested changes
I agree with @dominik-zeglen, we should use query params to open the channel picker dialog.

2020-11-23 11:29 UTC, dominik-zeglen approved these changes

2020-11-23 11:29 UTC, mmarkusik approved these changes

2020-11-23 11:31 UTC, orzechdev approved these changes
I agree with what @dominik-zeglen said

2020-11-23 11:31 UTC, merged