fix SaleCreate view
mirumee/saleor-dashboard pull request #857
Opened 2020-11-24 11:08 UTC by AlicjaSzu

I want to merge this change because...
- it fixes sale create bug

### Screenshots

<img width="1275" alt="Screenshot 2020-11-24 at 11 44 01" src="https://user-images.githubusercontent.com/10812388/100086438-b50fc080-2e4d-11eb-80d1-2a2f01fa72d7.png">

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-11-24 11:10 UTC, patrys commented
Task linked: [SALEOR-1696 [BUG][SALES] Available channels resets after Save](https://app.clickup.com/t/2549495/SALEOR-1696)

2020-11-24 13:35 UTC, krzysztofwolski requested changes
One change to make - after creating Sale message with success is displayed as Info (gray background) instead of Success (green). Besides that all is ok.

2020-11-25 10:22 UTC, krzysztofwolski approved these changes

2020-11-25 15:52 UTC, orzechdev approved these changes

2020-11-26 09:10 UTC, mlamperski commented
Tested on deployed environment. Issue doesn't occur anymore.

2020-11-26 10:43 UTC, merged