disable Manage channels for user without permission
mirumee/saleor-dashboard pull request #858
Opened 2020-11-24 15:15 UTC by AlicjaSzu

I want to merge this change because...

- it hides MANAGE channels button when user doesn't have proper permission.

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-11-24 15:27 UTC, patrys commented
Task linked: [SALEOR-1638 Product availability section management not disabled for user without permissions](https://app.clickup.com/t/2549495/SALEOR-1638)

2020-11-25 13:36 UTC, mmarkusik commented on src/components/ChannelsAvailability/ChannelsAvailabilityWithPermission.tsx
> +import { hasPermission } from "@saleor/auth/misc";
@AlicjaSzu an meself figured it'd make more sense to make a general permissions wrapper component for these kind of situations

2020-11-25 13:36 UTC, mmarkusik approved these changes

2020-11-25 16:28 UTC, orzechdev requested changes

2020-11-25 16:28 UTC, orzechdev commented on src/components/ChannelsAvailability/ChannelsAvailabilityWithPermission.tsx
> +      hasManageChannelsPermission={hasManageChannelsPermission}
`ChannelsAvailability` doesn't need to know anything about permissions, I would change it to something like: 
```suggestion
      manageChannels={hasManageChannelsPermission}
```
as the `ChannelsAvailability` component would only care about whether managing channels UI within it should be displayed, while a decision on when it should be displayed, e.g. when permission is available, would be left for upper layer components.

2020-11-30 11:24 UTC, dominik-zeglen requested changes
Replicating `src/components/RequirePermissions.tsx`

2020-11-30 12:52 UTC, krzysztofwolski approved these changes

2020-11-30 12:58 UTC, orzechdev approved these changes

2020-11-30 13:08 UTC, merged