Saleor 1680 add shipping methods to translation section
mirumee/saleor-dashboard pull request #864
Opened 2020-11-26 13:37 UTC by MarekChoinski

I want to merge this change because it adds tab "Shipping methods" in Translations

**PR intended to be tested with API branch:** 

### Screenshots

<img width="994" alt="image" src="https://user-images.githubusercontent.com/29279389/100357159-94ce3600-2ff4-11eb-8811-adb5b25ca13a.png">

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/29279389/100357205-a9123300-2ff4-11eb-925c-844daf8ee060.png">

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-11-26 13:37 UTC, patrys commented
Task linked: [SALEOR-1680 Add Shipping Methods to translation section](https://app.clickup.com/t/2549495/SALEOR-1680)

2020-11-26 17:10 UTC, krzysztofwolski requested changes

2020-11-26 17:10 UTC, krzysztofwolski commented on src/translations/mutations.ts
> +    shippingPriceTranslate(id: $id, input: $input, languageCode: $language) {
```suggestion
    shippingMethodTranslate(id: $id, input: $input, languageCode: $language) {
```

2020-11-27 10:45 UTC, AlicjaSzu approved these changes

2020-11-27 15:53 UTC, krzysztofwolski approved these changes

2020-11-27 15:53 UTC, merged