Saleor 1662 sort just added channel availability
mirumee/saleor-dashboard pull request #878
Opened 2020-11-30 14:36 UTC by MarekChoinski

I want to merge this change because it adds sorting on local changes of channels on product update page.

**PR intended to be tested with API branch:** 

### Screenshots

<img width="407" alt="image" src="https://user-images.githubusercontent.com/29279389/100622987-d4ad5a00-3321-11eb-9967-b3f570c1113d.png">

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-11-30 14:37 UTC, patrys commented
Task linked: [SALEOR-1662 Sort just added channel availability](https://app.clickup.com/t/2549495/SALEOR-1662)

2020-11-30 15:30 UTC, krzysztofwolski approved these changes
Tested - works as intended

2020-11-30 15:47 UTC, krzysztofwolski requested changes
Changed review - we are using the same component in many pages. Sorting should be handled in one place.

2020-11-30 19:05 UTC, krzysztofwolski approved these changes

2020-12-01 10:03 UTC, AlicjaSzu approved these changes

2020-12-01 10:48 UTC, orzechdev approved these changes

2020-12-01 11:26 UTC, merged