Fix null voucher name handle
mirumee/saleor-dashboard pull request #891
Opened 2020-12-07 11:43 UTC by MarekChoinski

I want to merge this change because... it fixes handling null voucher name in Translations

**PR intended to be tested with API branch:** 

### Screenshots

before:
![image](https://user-images.githubusercontent.com/29279389/101347053-c1ead600-3889-11eb-8efb-be78c156fcd4.png)

after:
![image](https://user-images.githubusercontent.com/29279389/101347067-c7e0b700-3889-11eb-8e56-7d8c76d9d94f.png)

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-12-07 11:45 UTC, patrys commented
Task linked: [SALEOR-1668 Handle null voucher name in Translations page](https://app.clickup.com/t/2549495/SALEOR-1668)

2020-12-08 11:36 UTC, MarekChoinski commented
after:
![obraz](https://user-images.githubusercontent.com/29279389/101479073-e9a57100-3951-11eb-9808-9f52c4d2aa6e.png)

2020-12-08 11:45 UTC, orzechdev requested changes
The same issue still occurs on voucher list page in test-env-s, probably because some vouchers doesn't use any channel. As this is the part of task, please investigate it too.

2020-12-08 17:40 UTC, krzysztofwolski approved these changes

2020-12-09 09:59 UTC, orzechdev approved these changes
Bug occurs on test-envs, but I guess there is a bug with not updated deployment.

2020-12-09 10:15 UTC, merged