Shipping zone description
mirumee/saleor-dashboard pull request #926
Opened 2020-12-30 12:35 UTC by tomaszszymanski129

I want to merge this change because it adds description to shipping zone.

Backend: https://github.com/mirumee/saleor/pull/6653

Related ticket: [SALEOR-1017](https://app.clickup.com/t/2549495/SALEOR-1017)

**PR intended to be tested with API branch:** SALEOR-1017-shipping-rate-description

### Screenshots

![image](https://user-images.githubusercontent.com/12252472/103351542-de9eb600-4aa3-11eb-93cc-f8b0ef58f864.png)

### Pull Request Checklist

1. [X] All visible strings are translated with proper context.
1. [X] All data-formatting is locale-aware (dates, numbers, and so on).
1. [X] Translated strings are extracted.
1. [X] Number of API calls is optimized.
1. [X] The changes are tested.
1. [X] Data-test are added for new elements.
1. [X] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2020-12-30 12:35 UTC, patrys commented
Task linked: [SALEOR-1017 As a User I want to add description to the shipping rate](https://app.clickup.com/t/2549495/SALEOR-1017)

2021-01-04 09:25 UTC, mmarkusik commented on src/shipping/components/ShippingZoneDetailsPage/ShippingZoneDetailsPage.tsx
> +const maxDescriptionLength = 300;
Nothing big, but maybe when making consts outside of the component function it'd be easier to tell apart from local component consts if the const was like so MAX_DESCRIPTION_LENGTH?

2021-01-04 09:25 UTC, mmarkusik approved these changes

2021-01-04 20:32 UTC, MarekChoinski approved these changes

2021-01-04 20:32 UTC, MarekChoinski commented on src/shipping/components/ShippingZoneDetailsPage/ShippingZoneDetailsPage.tsx
> +                        <FormattedMessage
Nothing big, but in this file there are a lot of `defaultMessage`. We can move all messages into `const messages = defineMessages({...})`

2021-01-05 11:35 UTC, MarekChoinski approved these changes

2021-01-07 08:37 UTC, jwm0 approved these changes

2021-01-07 08:43 UTC, jwm0 requested changes
I'd suggest putting this field inside "General Information" section, the input outside the section looks out of the place and I couldn't find any designs that place it there.

2021-01-07 12:11 UTC, jwm0 approved these changes

2021-01-07 12:13 UTC, merged