Saleor 1861 - add error handling to returns form
mirumee/saleor-dashboard pull request #945
Opened 2021-01-13 12:03 UTC by mmarkusik

I want to merge this change because it adds error handling to returns page

**PR intended to be tested with API branch:** 

### Screenshots

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### Test environment config

API_URI=https://master.staging.saleor.rocks/graphql/

2021-01-13 12:03 UTC, patrys commented
Task linked: [SALEOR-1861 Add error handling to fulfilment lines](https://app.clickup.com/t/2549495/SALEOR-1861)

2021-01-13 12:30 UTC, dominik-zeglen requested changes

2021-01-13 12:30 UTC, dominik-zeglen commented on src/orders/components/OrderReturnPage/OrderReturnRefundItemsCard/ProductErrorCell.tsx
> +      backgroundColor: "#FE6D76",
Shouldn't it come from `theme.palette`?

2021-01-13 12:30 UTC, dominik-zeglen commented on src/orders/components/OrderReturnPage/OrderReturnRefundItemsCard/ProductErrorCell.tsx
> +      padding: `${theme.spacing(2)}px ${theme.spacing(3)}px`,
```suggestion
      padding: theme.spacing(2, 3),
```

2021-01-13 12:30 UTC, dominik-zeglen commented on src/orders/components/OrderReturnPage/OrderReturnRefundItemsCard/ProductErrorCell.tsx
> +      position: "absolute",
If I were you I'd use `Popper`

2021-01-14 21:45 UTC, jwm0 approved these changes
Apart from what @dominik-zeglen mentioned it looks good 👍

2021-01-18 15:19 UTC, dominik-zeglen approved these changes

2021-01-18 15:20 UTC, dominik-zeglen requested changes

2021-01-18 15:20 UTC, dominik-zeglen commented on src/orders/components/OrderReturnPage/OrderReturnRefundItemsCard/ProductErrorCell.tsx
> +import { makeStyles, TableCell, Typography } from "@material-ui/core";
This could use some deep importing

2021-01-19 09:25 UTC, merged