Update API url
mirumee/saleor-dashboard pull request #957
Opened 2021-01-22 10:11 UTC by dominik-zeglen

Self explanatory

2021-01-22 12:51 UTC, krzysztofwolski commented
@dominik-zeglen can we also update GH Actions? Test envs for this release were pointing to .rocks domain

2021-01-22 13:16 UTC, jwm0 approved these changes
✨

2021-01-25 13:46 UTC, cmiacz requested changes

2021-01-25 13:46 UTC, cmiacz commented on .github/workflows/test-env-deploy.yml
> -          echo "::set-output name=domain::${{ env.GITHUB_HEAD_REF_SLUG_URL }}.dashboard.saleor.rocks"
It should not be modified. Test environments are hosted outside cloud, under saleor.rocks domain.

2021-01-25 13:46 UTC, cmiacz commented on .github/workflows/test-env-cleanup.yml
> -          echo "::set-output name=domain::${{ env.GITHUB_HEAD_REF_SLUG_URL }}.dashboard.saleor.rocks"
It should not be modified. Test environments are hosted outside cloud, under saleor.rocks domain.

2021-01-25 13:47 UTC, closed without merging