Handle limit reached error
mirumee/saleor-dashboard pull request #990
Opened 2021-02-24 11:55 UTC by dominik-zeglen

I want to merge this change because it handles `LimitReachedError` in graphql protocol.

**PR intended to be tested with API branch:** 

### Screenshots
<img width="1680" alt="Screenshot 2021-02-24 at 12 27 34" src="https://user-images.githubusercontent.com/6833443/108997139-8c42d580-769f-11eb-9648-49cb258d615f.png">

### Pull Request Checklist

1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Translated strings are extracted.
1. [ ] Number of API calls is optimized.
1. [ ] The changes are tested.
1. [ ] Data-test are added for new elements.
1. [ ] Type definitions are up to date.
1. [x] Changes are mentioned in the changelog.
1. [ ] The changes are tested in different browsers (Chrome, Firefox, Safari).
1. [ ] The changes are tested in light and dark mode.

### Test environment config

API_URI=https://master.staging.saleor.cloud/graphql/

2021-02-24 11:56 UTC, patrys commented
Task linked: [SALEOR-2180 Handle limitation errors in saleor-dashboard](https://app.clickup.com/t/2549495/SALEOR-2180)

2021-02-24 12:37 UTC, patrys commented on src/intl.ts
> +    defaultMessage: "Reached limit for this plan"
It should explicitly say: "Already at the limit. Unable to create more users." No need to refer to "this plan."

2021-02-24 12:38 UTC, patrys requested changes
In the screenshot, the error is a toast hidden behind the overlay. Ideally, it should be presented within the modal.

2021-02-25 09:15 UTC, dominik-zeglen commented
@patrys should we completely remove toast?

<img width="1680" alt="Screenshot 2021-02-25 at 10 14 46" src="https://user-images.githubusercontent.com/6833443/109130731-59a5e500-7752-11eb-97ec-42a6ec63a8a5.png">

2021-02-25 10:31 UTC, jwm0 commented
> @patrys should we completely remove toast?
> 
> <img alt="Screenshot 2021-02-25 at 10 14 46" width="1680" src="https://user-images.githubusercontent.com/6833443/109130731-59a5e500-7752-11eb-97ec-42a6ec63a8a5.png">

I'd keep the toast to be consistent across other gql errors but move its z-index so it's not hidden by the modal backdrop

2021-03-08 11:46 UTC, jwm0 approved these changes

2021-03-08 14:51 UTC, merged